spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    content-type: text/html
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver